version: "3.9"

services:
  advancing-film-api:
    image: advancing-film-api
    labels:
      - traefik.enable=true
      - traefik.http.routers.advancing-film-api.rule=PathPrefix(`/fetch/external`)
    expose:
      - 8080
    networks:
      - traefik-net
    ports:
      - "9090:9090"
networks:
  traefik-net:
    external: true
