version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
      - --api.insecure=true
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
